# Generated by Django 5.0 on 2026-07-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='focus_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
