# Generated by Django 5.0 on 2026-08-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_session_leader_leadrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leadrequest',
            unique_together=set(),
        ),
    ]
