# Generated by Django 5.0 on 2026-08-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_leadrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='zoom_join_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='zoom_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='zoom_start_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
