# Generated by Django 5.0 on 2026-08-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_password_reset_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='zoom_join_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='zoom_start_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
