# Generated by Django 5.0 on 2026-08-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_increase_zoom_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='session',
            name='last_regenerated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='regenerate_interval_hours',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='session',
            name='type',
            field=models.CharField(choices=[('sprint', 'Focus Sprint'), ('deep-work', 'Deep Work'), ('marathon', 'Marathon'), ('ongoing', 'Ongoing Call')], max_length=20),
        ),
    ]
