# Generated by Django 5.0 on 2026-09-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_package_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Unique setting key', max_length=255, unique=True)),
                ('value', models.TextField(help_text="Setting value (encrypted if type is 'encrypted')")),
                ('category', models.CharField(choices=[('frontend', 'Frontend Settings'), ('backend', 'Backend Settings'), ('general', 'General Settings')], default='general', max_length=20)),
                ('setting_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('json', 'JSON'), ('encrypted', 'Encrypted String')], default='string', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting does')),
                ('is_encrypted', models.BooleanField(default=False, help_text='Whether this value should be encrypted')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this setting can be accessed by non-admin users')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
                'ordering': ['category', 'key'],
            },
        ),
    ]
