# Generated by Django 5.0 on 2026-09-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='trial_days',
            field=models.IntegerField(default=0, help_text='Number of trial days for this package'),
        ),
    ]
