# Generated by Django 5.0 on 2026-09-18 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_enhance_purchase_payment_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('other', 'Other')], default='card', max_length=20)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4, null=True)),
                ('card_expiry_month', models.CharField(blank=True, help_text='Card expiry month (MM)', max_length=2, null=True)),
                ('card_expiry_year', models.CharField(blank=True, help_text='Card expiry year (YYYY)', max_length=4, null=True)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (visa, mastercard, etc.)', max_length=20, null=True)),
                ('paystack_auth_code', models.CharField(blank=True, help_text='Paystack authorization code', max_length=255, null=True)),
                ('paystack_token', models.CharField(blank=True, help_text='Paystack payment token', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default payment method')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
