# Generated by Django 5.0 on 2026-09-19 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('session_booking', 'Session Booking'), ('session_cancellation', 'Session Cancellation'), ('session_completion', 'Session Completion'), ('lead_request', 'Lead Request'), ('lead_request_approved', 'Lead Request Approved'), ('lead_request_rejected', 'Lead Request Rejected'), ('purchase', 'Purchase'), ('subscription_renewal', 'Subscription Renewal'), ('subscription_expiry', 'Subscription Expiry'), ('login', 'User Login'), ('profile_update', 'Profile Update')], max_length=50)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the activity')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional activity data as JSON')),
                ('sessions_consumed', models.IntegerField(default=0, help_text='Number of session credits consumed')),
                ('lead_requests_consumed', models.IntegerField(default=0, help_text='Number of lead request credits consumed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.leadrequest')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.purchase')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Activities',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_useract_user_id_496f54_idx'), models.Index(fields=['activity_type', '-created_at'], name='api_useract_activit_285e3d_idx'), models.Index(fields=['created_at'], name='api_useract_created_1328f5_idx')],
            },
        ),
    ]
